name: qa_pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests with @automation-api tag
        run: mvn test -Dcucumber.filter.tags="@automation-api"
        working-directory: ./path/to/your/project