name: qa_pipeline

on:
  workflow_dispatch:
    inputs:
        tags:
          description: 'Tags de prueba'
          required: true
          default: '@automation-api'
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: CLonacion del repositorio
        uses: actions/checkout@v4

      - name: Instalacion
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Ejecutar pruebas con tag
        run: mvn clean test -Dkarate.tags=${{ inputs.tags }} -Dmaven.test.failure.ignore=true

      - name: Visualizar reporte de Karate
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karate-reports
          path: target/karate-reports/