name: qa_pipeline

on:
  workflow_dispatch:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Run tests with @automation-api tag
        run: mvn test -Dcucumber.filter.tags="@automation-api"